# foreman start -m gateway=1,app=3,timelines=3,directMessaging=3
gateway: cd ../gateway && FLASK_APP=gateway flask run -p $PORT
app: cd ../gateway && FLASK_APP=app flask run -p $PORT
timelines: cd ../gateway && FLASK_APP=timelines flask run -p $PORT
directMessaging: FLASK_APP=directMessaging flask run -p $PORT
